# Check out https://hub.docker.com/_/node to select a new base image
FROM node:18-slim

RUN apt update && apt install -y \
    git \
    curl \
    bash

RUN touch /root/.bashrc | echo "PS1='\w\$ '" >> /root/.bashrc

RUN mkdir -p /home/node/app
RUN npm config set cache /home/node/app/.npm-cache --global
RUN npm install -g nodemon
RUN npm install -g @loopback/cli npm@9.8.1

# Set to a non-root built-in user `node`
USER node

# Create app directory (with user `node`)
WORKDIR /home/node/app
