# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# You can remove 'includes' or add empty files when no data is necessary
automation: !include automations.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml
scene: !include scenes.yaml

# Accessing raw sensors data from files as part of the sysfs interface
# to hwmon. Using RPi OS, take a look under /sys/class/.
#
# https://www.kernel.org/doc/Documentation/hwmon/sysfs-interface
#
# Naming and data format standards for sysfs files:
#
#   The libsensors library offers an interface to the raw sensors data
#   through the sysfs interface. Since lm-sensors 3.0.0, libsensors is
#   completely chip-independent. It assumes that all the kernel drivers
#   implement the standard sysfs interface described in this document.
#
command_line:
  - sensor:
      name: 'RPi CPU temperature'
      command: "cat /sys/class/thermal/cooling_device0/subsystem/thermal_zone0/temp"
      scan_interval: 15
      value_template: "{{ value | multiply(0.001) | round(1) }}"
      device_class: temperature
      unit_of_measurement: "°C"
  - sensor:
      name: 'RPi PoE online'
      command: "cat /sys/class/power_supply/rpi-poe/hwmon1/device/subsystem/rpi-poe/online"
      scan_interval: 5
      value_template: "{{ value }}"
  - sensor:
      name: 'RPi PoE current'
      command: "cat /sys/class/power_supply/rpi-poe/hwmon1/device/subsystem/rpi-poe/current_now"
      scan_interval: 5
      value_template: "{{ value | multiply(0.001) | round(1) }}"
      device_class: current
      unit_of_measurement: "mA"
  - sensor:
      name: 'RPi PoE max'
      command: "cat /sys/class/power_supply/rpi-poe/hwmon1/device/subsystem/rpi-poe/current_max"
      scan_interval: 5
      value_template: "{{ value | multiply(0.001) | round(1) }}"
      device_class: current
      unit_of_measurement: "mA"
  - sensor:
      name: 'RPi PoE status'
      command: "cat /sys/class/power_supply/rpi-poe/hwmon1/device/subsystem/rpi-poe/health"
      scan_interval: 5
      value_template: "{{ value }}"
  - sensor:
      name: 'Pwm state'
      command: "cat /sys/class/thermal/cooling_device0/cur_state"
      scan_interval: 5
      value_template: "{{ value }}"
  - sensor:
      name: 'Pwm state max'
      command: "cat /sys/class/thermal/cooling_device0/max_state"
      scan_interval: 5
      value_template: "{{ value }}"
  - sensor:
      name: 'Pwm speed'
      command: "cat /sys/class/hwmon/hwmon3/device/hwmon/hwmon3/pwm1"
      scan_interval: 5
      value_template: "{{ value }}"
      device_class: speed
      unit_of_measurement: "rpm"

# Unflashed SONOFF devices
#sonoff:
#  username: xuser
#  password: xpass
#  reload: always
