- platform: template
  lights:
    office_led_strip:
      friendly_name: "Office LED Strip"
      value_template: "{{ states('switch.office_led_strip') == 'on' }}"
      color_template: "({{ states('input_number.office_led_strip_hue') | int}}, {{ states('input_number.office_led_strip_sat') | int}})"
      turn_off:
        service: switch.turn_off
        target:
          entity_id: switch.office_led_strip
      turn_on:
        service: switch.turn_on
        target:
          entity_id: switch.office_led_strip
      set_level:
        - service: input_number.set_value
          data:
            value: "{{ brightness }}"
            entity_id: input_number.office_led_strip_brightness
        - service: switch.turn_on
          data_template:
            entity_id:
              - switch.office_led_strip
      set_color:
        - service: input_number.set_value
          data:
            value: "{{ h }}"
            entity_id: input_number.office_led_strip_hue
        - service: input_number.set_value
          data:
            value: "{{ s }}"
            entity_id: input_number.office_led_strip_sat
        - service: switch.turn_on
          data_template:
            entity_id:
              - switch.office_led_strip

