- platform: rest
  name: distance
  resource: http://127.0.0.1:5000/test
  body_on: '{"first": "0","size": "2","line": "5","on": true, "hue": {{ states("input_number.office_led_strip_hue") }}, "sat": {{ states("input_number.office_led_strip_sat") }}, "brightness": {{ states("input_number.office_led_strip_brightness") }}}'
  body_off: '{"first": "0","size": "2","line": "5","on": false}'
  is_on_template: '{{ value_json.on }}'
  headers:
    Content-Type: application/json

- platform: rest
  name: status
  resource: http://127.0.0.1:5000/status
  body_on: '{"first": "2","size": "2","line": "5","on": true, "hue": {{ states("input_number.office_led_strip_hue") }}, "sat": {{ states("input_number.office_led_strip_sat") }}, "brightness": {{ states("input_number.office_led_strip_brightness") }}}'
  body_off: '{"first": "2","size": "2","line": "5","on": false}'
  is_on_template: '{{ value_json.on }}'
  headers:
    Content-Type: application/json
