# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Unflashed SONOFF devices
sonoff:
  username: josemotta@bampli.com
  password: tiagomotta
  reload: always

switch: !include switch.yaml
light: !include light.yaml
